# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/speaking-plants',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/speaking-plants',
                'lib_path': 'speaking_plants'},
  'syms': {'speaking_plants.core': {'speaking_plants.core.foo': ('core.html#foo', 'speaking_plants/core.py')}}}
