# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/speaking-plants',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/speaking-plants',
                'lib_path': 'speaking_plants'},
  'syms': { 'speaking_plants.clean': { 'speaking_plants.clean._rows2df': ('clean.html#_rows2df', 'speaking_plants/clean.py'),
                                       'speaking_plants.clean.clean': ('clean.html#clean', 'speaking_plants/clean.py'),
                                       'speaking_plants.clean.find_gaps': ('clean.html#find_gaps', 'speaking_plants/clean.py'),
                                       'speaking_plants.clean.frames': ('clean.html#frames', 'speaking_plants/clean.py'),
                                       'speaking_plants.clean.qc_report': ('clean.html#qc_report', 'speaking_plants/clean.py'),
                                       'speaking_plants.clean.read_log': ('clean.html#read_log', 'speaking_plants/clean.py'),
                                       'speaking_plants.clean.read_logs': ('clean.html#read_logs', 'speaking_plants/clean.py')}}}
