"""Read microcontroller SD-card logs into one flat, quality-flagged DataFrame

Docs: https://franckalbinet.github.io/speaking-plants/clean.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_clean.ipynb.

# %% auto #0
__all__ = ['ruuvi_cols', 'soil_cols', 'leaf_cols', 'px_cols', 'id_cols', 'schema', 'raw_id_cols', 'common', 'layouts', 'limits',
           'read_log', 'read_logs', 'clean', 'measurements', 'frames', 'qc_report', 'find_gaps']

# %% ../nbs/00_clean.ipynb #49706bda
import numpy as np, pandas as pd
from fastcore.utils import *


# %% ../nbs/00_clean.ipynb #ab72d14a
ruuvi_cols = ['ruuvi_temp', 'ruuvi_humidity', 'ruuvi_pressure']
soil_cols = ['soil_moisture', 'soil_temperature']
leaf_cols = ['leaf_temp_mean', 'leaf_temp_max', 'leaf_temp_min']
px_cols = [f'pixel_{i}' for i in range(768)]
id_cols = ['node_id', 'time', 'timestamp', 'measurement_id', 'frame']
schema = id_cols + ruuvi_cols + soil_cols + leaf_cols + px_cols

# %% ../nbs/00_clean.ipynb #b880333d
raw_id_cols = ['node_id', 'measurement_id', 'frame', 'timestamp', 'date', 'time']
common = soil_cols + leaf_cols + px_cols
layouts = {len(o): o for o in (raw_id_cols + common, raw_id_cols + ruuvi_cols + common)}


# %% ../nbs/00_clean.ipynb #deb1fea8
def _rows2df(rows, cols):
    a, n = np.array(rows), len(raw_id_cols)
    ids = pd.DataFrame(dict(node_id=np.char.strip(a[:, 0]), time=pd.to_datetime(a[:, 3].astype(int), unit='s')))
    ids[['measurement_id', 'frame', 'timestamp']] = a[:, 1:4].astype(int)
    vals = pd.DataFrame(a[:, n:].astype(float), columns=cols[n:]).reindex(columns=ruuvi_cols + common)
    return pd.concat([ids, vals], axis=1)[schema]

def read_log(
    path, # CSV log written by one node
)->pd.DataFrame: # One row per frame, columns in `schema` order, sorted by time and frame
    "Read one node's log into the common schema"
    rows = {}
    with open(path) as f:
        next(f)
        for l in f:
            fs = l.rstrip('\r\n').split(';' if ';' in l else ',')
            rows.setdefault(len(fs), []).append(fs)
    if unknown := set(rows) - set(layouts): raise ValueError(f'{path}: rows with {sorted(unknown)} fields match no known layout')
    df = pd.concat([_rows2df(v, layouts[n]) for n,v in rows.items()]).replace(-999, np.nan)
    return df.sort_values(['time', 'frame'], ignore_index=True)

# %% ../nbs/00_clean.ipynb #99c306d0
def read_logs(
    paths, # CSV logs, one or more per node
)->pd.DataFrame: # One row per frame for all nodes, sorted by node, time and frame
    "Read logs from all nodes into one table"
    df = pd.concat([read_log(p) for p in paths], ignore_index=True)
    return df.sort_values(['node_id', 'time', 'frame'], ignore_index=True)

# %% ../nbs/00_clean.ipynb #e609ba6b
limits = dict(pixel=(0, 60), soil_moisture=(0, 100), soil_temperature=(0, 60))

# %% ../nbs/00_clean.ipynb #441a987e
def _leaf(p): return pd.DataFrame(dict(leaf_temp_mean=p.mean(axis=1), leaf_temp_max=p.max(axis=1), leaf_temp_min=p.min(axis=1)))
def clean(
    df:pd.DataFrame, # Output of `read_logs`
    limits:dict=limits, # Open interval of plausible values per measurement
)->pd.DataFrame: # Same rows, implausible values missing, with `qc_*` flag columns
    "Set implausible values to missing, flag them, and recompute leaf summaries from the remaining pixels"
    bad = lambda x, k: (x <= limits[k][0]) | (x >= limits[k][1])
    p = df[px_cols].mask(bad(df[px_cols], 'pixel'))
    soil = pd.DataFrame({c: df[c].mask(bad(df[c], c)) for c in soil_cols})
    leaf = _leaf(p)
    n_bad_px = (p.isna() & df[px_cols].notna()).sum(axis=1)
    soil_lost = (soil.isna() & df[soil_cols].notna()).any(axis=1)
    qc = pd.DataFrame(dict(qc_bad_px=n_bad_px, qc_soil=soil_lost))
    return pd.concat([df[id_cols + ruuvi_cols], soil, leaf, qc, p], axis=1)

# %% ../nbs/00_clean.ipynb #d2e61347
def measurements(
    df:pd.DataFrame, # Output of `clean`
)->pd.DataFrame: # One row per node and time, with the median image of the burst
    "Combine each burst of frames into one measurement"
    g = df.groupby(['node_id', 'time'])
    p = g[px_cols].median()
    ids = g[['timestamp', 'measurement_id']].first().assign(n_frames=g.size())
    env = g[ruuvi_cols + soil_cols].median()
    qc = g.agg(qc_bad_px=('qc_bad_px', 'sum'), qc_soil=('qc_soil', 'any'))
    return pd.concat([ids, env, _leaf(p), qc, p], axis=1).reset_index()

# %% ../nbs/00_clean.ipynb #c691acbc
def frames(
    df:pd.DataFrame, # Rows of `read_logs`, `clean` or `measurements` output
)->np.ndarray: # Shape `(len(df), 24, 32)`, one thermal image per row
    "Thermal images of the frames in `df`"
    return df[px_cols].to_numpy().reshape(-1, 24, 32)

# %% ../nbs/00_clean.ipynb #340a764f
def qc_report(
    df:pd.DataFrame, # Output of `clean`
    max_step='15min', # Longest expected interval between measurements
)->pd.DataFrame: # One row per node
    "Per-node summary of coverage, gaps and quality flags"
    def _node(d):
        t = d.time.drop_duplicates()
        gaps = t.diff()
        res = dict(frames=len(d), measurements=len(t), first=t.min(), last=t.max())
        res |= dict(gaps=(gaps > pd.Timedelta(max_step)).sum(), longest_gap=gaps.max())
        res |= {f'{c}_%': round(100*d[c].notna().mean(), 1) for c in ['ruuvi_temp', *soil_cols]}
        res |= dict(frames_bad_px=(d.qc_bad_px > 0).sum(), frames_no_px=d.leaf_temp_mean.isna().sum(), soil_flagged=d.qc_soil.sum())
        return pd.Series(res)
    return df.groupby('node_id').apply(_node)

# %% ../nbs/00_clean.ipynb #9b227e31
def find_gaps(
    df:pd.DataFrame, # Output of `read_logs` or `clean`
    max_step='15min', # Longest expected interval between measurements
)->pd.DataFrame: # One row per gap: node, last measurement before it, first after it, and duration
    "Intervals longer than `max_step` without a measurement, per node"
    def _node(d):
        t = d.time.drop_duplicates()
        return pd.DataFrame(dict(node_id=d.node_id.iloc[0], start=t.shift(), end=t, duration=t.diff()))
    res = pd.concat([_node(d) for _,d in df.groupby('node_id')])
    return res[res.duration > pd.Timedelta(max_step)].reset_index(drop=True)
