"""Daily leaf temperature, its rate of change and leaf minus air temperature, per node

Docs: https://franckalbinet.github.io/speaking-plants/leaf.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_leaf.ipynb.

# %% auto #0
__all__ = ['site', 'regimes', 'full_days', 'std_map', 'top_mask', 'daily_masks', 'batch_masks', 'no_masks', 'regular', 'smooth',
           'slope', 'vpd', 'leaf_series', 'plot_panels', 'sun_times', 'is_day', 'scene_similarity',
           'plot_scene_similarity', 'periods', 'node_table', 'combine', 'pair_stats', 'scatter_matrix', 'peers',
           'daily_fits']

# %% ../nbs/01_leaf.ipynb #55038a45
import itertools
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from scipy.signal import savgol_filter
from .clean import frames
from astral import LocationInfo
from astral.sun import sun

# %% ../nbs/01_leaf.ipynb #176025ec
def full_days(
    df:pd.DataFrame, # Output of `measurements`
    min_n:int=280, # Fewest measurements for a full day
)->pd.DataFrame: # One row per full day, with `node_id` and `day`
    "Node-days with at least `min_n` measurements"
    n = df.groupby(['node_id', df.time.dt.normalize().rename('day')]).size()
    return n[n >= min_n].reset_index()[['node_id', 'day']]

# %% ../nbs/01_leaf.ipynb #630bb15d
def std_map(
    df:pd.DataFrame, # Rows of `measurements` output
)->np.ndarray: # Shape `(24, 32)`, standard deviation of each pixel over the rows
    "Standard deviation of each pixel over time"
    return np.nanstd(frames(df), axis=0)

def top_mask(
    sd:np.ndarray, # Output of `std_map`
    q:float=0.9, # Quantile above which a pixel counts as leaf
)->np.ndarray: # Boolean, same shape as `sd`
    "Pixels whose standard deviation is above the `q` quantile"
    return sd > np.nanquantile(sd, q)

# %% ../nbs/01_leaf.ipynb #9f4dd703
def _day(df, node, day): return df[(df.node_id == node) & (df.time.dt.normalize() == day)]

def daily_masks(
    df:pd.DataFrame, # Output of `measurements`
    days:pd.DataFrame, # Output of `full_days`
    q:float=0.9, # Quantile above which a pixel counts as leaf
)->dict: # Mask per `(node_id, day)`, from that day's images
    "One leaf mask per node-day, from that day"
    return {(r.node_id, r.day): top_mask(std_map(_day(df, r.node_id, r.day)), q) for r in days.itertuples()}

def batch_masks(
    df:pd.DataFrame, # Output of `measurements`
    days:pd.DataFrame, # Output of `full_days`
    q:float=0.9, # Quantile above which a pixel counts as leaf
)->dict: # Mask per `(node_id, day)`, from all of the node's images
    "One leaf mask per node, from all its images, repeated for each of its days"
    ms = {n: top_mask(std_map(g), q) for n, g in df.groupby('node_id')}
    return {(r.node_id, r.day): ms[r.node_id] for r in days.itertuples()}

def no_masks(
    days:pd.DataFrame, # Output of `full_days`
)->dict: # All-pixel mask per `(node_id, day)`
    "Masks that keep every pixel, for the unmasked profile"
    return {(r.node_id, r.day): np.ones((24, 32), bool) for r in days.itertuples()}

# %% ../nbs/01_leaf.ipynb #fee733f2
def regular(
    s:pd.Series, # Values indexed by time
    step:str='5min', # Grid step
)->pd.Series: # Values on a grid from the first time, missing where no value is within half a step
    "Put a time series on a regular grid"
    grid = pd.date_range(s.index[0], s.index[-1], freq=step, name='time')
    return s.reindex(grid, method='nearest', tolerance=pd.Timedelta(step) / 2)

def _savgol(s, window, polyorder, deriv):
    "Savitzky-Golay filter on each stretch of `s` without missing values, per minute"
    step = s.index.freq.nanos / 60e9
    out, ok = pd.Series(np.nan, index=s.index), s.notna()
    for _, v in s[ok].groupby((ok != ok.shift()).cumsum()[ok]):
        if len(v) >= window: out[v.index] = savgol_filter(v.to_numpy(), window, polyorder, deriv=deriv, delta=step)
    return out

def smooth(
    s:pd.Series, # Output of `regular`
    window:int=13, # Points in the Savitzky-Golay window
    polyorder:int=3, # Order of the fitted polynomial
)->pd.Series: # Smoothed values, missing on stretches shorter than `window`
    "Smoothed regular series"
    return _savgol(s, window, polyorder, 0)

def slope(
    s:pd.Series, # Output of `regular`
    window:int=9, # Points in the Savitzky-Golay window
    polyorder:int=3, # Order of the fitted polynomial
)->pd.Series: # Rate of change per minute, missing on stretches shorter than `window`
    "Smoothed first derivative of a regular series"
    return _savgol(s, window, polyorder, 1)

# %% ../nbs/01_leaf.ipynb #cbd42f79
def vpd(
    t, # Air temperature (°C)
    rh, # Relative humidity (%)
): # Vapour pressure deficit (kPa)
    "Vapour pressure deficit, with the Tetens formula for the saturation vapour pressure"
    return 0.6108 * np.exp(17.27 * t / (t + 237.3)) * (1 - rh / 100)

# %% ../nbs/01_leaf.ipynb #14e508e5
def leaf_series(
    df:pd.DataFrame, # Output of `share_ruuvi`
    masks:dict, # Output of `daily_masks`, `batch_masks` or `no_masks`
    step:str='5min', # Grid step
    window:int=9, # Points in the Savitzky-Golay window of `slope`
    polyorder:int=3, # Order of the fitted polynomial
    smooth_window:int=13, # Points in the smoothing window of `t_smooth` and `dt_smooth`
)->pd.DataFrame: # One row per grid time and node-day
    "Leaf temperature, air temperature and VPD, leaf minus air, raw and smoothed, and the leaf slope, per node-day"
    res = []
    for (node, day), mask in masks.items():
        g = _day(df, node, day)
        t = g.time.to_numpy()
        leaf = regular(pd.Series(np.nanmedian(frames(g)[:, mask], axis=1), index=t), step)
        air = regular(pd.Series(g.ruuvi_temp.to_numpy(), index=t), step)
        rh = regular(pd.Series(g.ruuvi_humidity.to_numpy(), index=t), step)
        res.append(pd.DataFrame(dict(node_id=node, day=day, t_leaf=leaf, t_smooth=smooth(leaf, smooth_window, polyorder),
                                     t_air=air, vpd=vpd(air, rh), dt_leaf_air=leaf - air, dt_smooth=smooth(leaf - air, smooth_window, polyorder),
                                     slope=slope(leaf, window, polyorder))).reset_index())
    out = pd.concat(res, ignore_index=True)
    out.insert(3, 'hour', (out.time - out.day).dt.total_seconds() / 3600)
    return out

# %% ../nbs/01_leaf.ipynb #fa522567
def plot_panels(
    df:pd.DataFrame, # Output of `leaf_series`
    col:str, # Column to plot against `hour`
    panel:str='node_id', # Column with one panel per value
    line:str='day', # Column with one line per value
    ylabel:str=None, # Label of the y axis, `col` by default
    title:str='', # Prefix of each panel title
):
    "Plot `col` against time of day, one panel per `panel` value and one line per `line` value"
    keys = sorted(df[panel].unique())
    fig, axs = plt.subplots(1, len(keys), figsize=(4.5 * len(keys), 3.2), sharey=True, squeeze=False)
    for ax, k in zip(axs[0], keys):
        for l, g in df[df[panel] == k].groupby(line):
            ax.plot(g.hour, g[col], lw=1, label=f'{l:%d %b}' if line == 'day' else l)
        ax.set_title(f'{title}{k:%d %b}' if panel == 'day' else f'{title}{k}', fontsize=10)
        ax.set_xticks(range(0, 25, 6)); ax.set_xlabel('hour'); ax.grid(alpha=0.3)
        ax.legend(fontsize=7)
    axs[0, 0].set_ylabel(ylabel or col)
    plt.tight_layout()

# %% ../nbs/01_leaf.ipynb #e3399195
site = LocationInfo('Seibersdorf', 'Austria', 'Europe/Vienna', 47.976, 16.508)

def sun_times(
    times, # Times or days, local time
    loc:LocationInfo=site, # Site of the greenhouse
)->pd.DataFrame: # One row per day, with dawn, sunrise, noon, sunset and dusk in local time
    "Sun events for each day in `times`"
    days = pd.DatetimeIndex(times).normalize().unique()
    evs = ('dawn', 'sunrise', 'noon', 'sunset', 'dusk')
    ss = [sun(loc.observer, date=d.date(), tzinfo=loc.timezone) for d in days]
    return pd.DataFrame({k: pd.to_datetime([s[k].replace(tzinfo=None) for s in ss]) for k in evs}, index=days.rename('day'))

def is_day(
    times, # Local times
    loc:LocationInfo=site, # Site of the greenhouse
)->np.ndarray: # True from sunrise to sunset
    "Whether each time is in daylight"
    t = pd.DatetimeIndex(times)
    st = sun_times(t, loc).reindex(t.normalize())
    return (t >= st.sunrise.to_numpy()) & (t < st.sunset.to_numpy())

# %% ../nbs/01_leaf.ipynb #6c012d76
def scene_similarity(
    df:pd.DataFrame, # Output of `measurements`
    min_n:int=144, # Fewest measurements for a day to be compared
)->dict: # Correlation matrix of daily standard deviation maps, per node
    "Correlation between the daily standard deviation maps of each node"
    res = {}
    for node, g in df.groupby('node_id'):
        maps = {d: std_map(gd).ravel() for d, gd in g.groupby(g.time.dt.normalize()) if len(gd) >= min_n}
        sim = pd.DataFrame(maps).corr()
        sim.index.name = sim.columns.name = 'day'
        res[node] = sim
    return res

def plot_scene_similarity(
    sim:dict, # Output of `scene_similarity`
):
    "One heatmap per node of the correlation between its days"
    fig, axs = plt.subplots(1, len(sim), figsize=(4.5 * len(sim), 4.2), squeeze=False)
    for ax, (node, m) in zip(axs[0], sim.items()):
        ax.imshow(m, vmin=0, vmax=1, cmap='viridis')
        labs = [f'{d:%d %b}' for d in m.index]
        ax.set_xticks(range(len(m)), labs, rotation=90, fontsize=7); ax.set_yticks(range(len(m)), labs, fontsize=7)
        for i, j in itertools.product(range(len(m)), repeat=2):
            ax.text(j, i, f'{m.iat[i, j]:.1f}', ha='center', va='center', fontsize=6, c='w' if m.iat[i, j] < 0.6 else 'k')
        ax.set_title(node, fontsize=10)
    plt.tight_layout()

# %% ../nbs/01_leaf.ipynb #cfaf2c53
def periods(
    bounds=(), # Dates of scene changes
)->dict: # Filter per period, for tables indexed by time
    "Split a time-indexed table at each date in `bounds`"
    b = [None] + list(pd.to_datetime(list(bounds))) + [None]
    def flt(s, e):
        def f(w):
            m = np.ones(len(w), bool)
            if s is not None: m &= w.index >= s
            if e is not None: m &= w.index < e
            return w[m]
        return f
    def name(s, e):
        if s is None and e is None: return 'all'
        if s is None: return f'before {e:%d %b}'
        if e is None: return f'from {s:%d %b}'
        return f'{s:%d %b} to {e:%d %b}'
    return {name(s, e): flt(s, e) for s, e in zip(b, b[1:])}

# %% ../nbs/01_leaf.ipynb #0aa35c69
def node_table(
    df:pd.DataFrame, # Output of `leaf_series`
    col:str, # Column to tabulate
)->pd.DataFrame: # One column per node, indexed by time rounded to 5 minutes
    "One column per node on a shared 5-minute time index"
    df = df.assign(t=df.time.dt.round('5min')).drop_duplicates(['node_id', 't'])
    return df.pivot(index='t', columns='node_id', values=col)

# %% ../nbs/01_leaf.ipynb #18357e9b
regimes = dict(night=lambda w: w[~is_day(w.index)], day=lambda w: w[is_day(w.index)])

def combine(
    periods:dict, # Output of `periods`
    regimes:dict=regimes, # Filter per regime
)->dict: # Filter per regime and period
    "Filters for each regime within each period"
    return {f'{r}, {p}': (lambda w, fr=fr, fp=fp: fr(fp(w))) for p, fp in periods.items() for r, fr in regimes.items()}

# %% ../nbs/01_leaf.ipynb #ce83eb1e
def pair_stats(
    w:pd.DataFrame, # Output of `node_table`, optionally with an `air` column
    groups:dict, # Filter per group of times, such as the output of `combine`
)->pd.DataFrame: # One row per pair and group
    "Bias, fitted line and correlation of `y` against `x`, for each pair of columns of `w` and each group"
    rows = []
    for (x, y), (p, f) in itertools.product(itertools.combinations(w.columns, 2), groups.items()):
        d = f(w)[[x, y]].dropna()
        if len(d) < 3: continue
        k, c0 = np.polyfit(d[x], d[y], 1)
        rows.append(dict(x=x, y=y, group=p, n=len(d), bias=(d[y] - d[x]).mean(), slope=k, intercept=c0, r=d[x].corr(d[y])))
    return pd.DataFrame(rows).round(2)

# %% ../nbs/01_leaf.ipynb #a3a7ffbf
def scatter_matrix(
    w:pd.DataFrame, # Output of `node_table`, optionally with an `air` column
    groups:dict=regimes, # Filter per group of times
    label:str='°C', # Unit of the axes
    title:str='', # Figure title
):
    "Pairwise scatter plots of the columns of `w`, with one fitted line per group"
    names = list(w.columns)
    fig, axs = plt.subplots(len(names), len(names), figsize=(2.6 * len(names), 2.6 * len(names)))
    lo, hi = np.nanmin(w.to_numpy()), np.nanmax(w.to_numpy())
    for i, j in itertools.product(range(len(names)), repeat=2):
        ax = axs[i, j]
        if j >= i:
            ax.axis('off')
            if i == j: ax.text(0.5, 0.5, names[i], ha='center', va='center', fontsize=12)
            continue
        for k, (p, f) in enumerate(groups.items()):
            d = f(w)[[names[j], names[i]]].dropna()
            if len(d) < 3: continue
            ax.scatter(d.iloc[:, 0], d.iloc[:, 1], s=2, alpha=0.3, c=f'C{k}', label=p)
            kk, c0 = np.polyfit(d.iloc[:, 0], d.iloc[:, 1], 1)
            ax.plot([lo, hi], [kk * lo + c0, kk * hi + c0], c=f'C{k}', lw=1.5)
        ax.plot([lo, hi], [lo, hi], c='k', ls='--', lw=0.8)
        ax.set_xlim(lo, hi); ax.set_ylim(lo, hi); ax.tick_params(labelsize=7)
        if j == 0: ax.set_ylabel(f'{names[i]} ({label})', fontsize=8)
        if i == len(names) - 1: ax.set_xlabel(f'{names[j]} ({label})', fontsize=8)
    axs[1, 0].legend(fontsize=7, markerscale=4)
    fig.suptitle(title)
    plt.tight_layout()

# %% ../nbs/01_leaf.ipynb #534d31a4
def peers(
    w:pd.DataFrame, # Output of `node_table`
)->pd.DataFrame: # Same shape as `w`
    "Mean of the other columns, for each column"
    return w.apply(lambda c: w.drop(columns=c.name).mean(axis=1))

# %% ../nbs/01_leaf.ipynb #1db26b15
def daily_fits(
    w:pd.DataFrame, # Output of `node_table`
    x, # Reference: a series shared by all nodes, or a table with the columns of `w`
    min_n:int=24, # Fewest points for a fit
)->pd.DataFrame: # One row per node, day and regime
    "Bias, slope, intercept and correlation of each node against `x`, per day and regime"
    day = is_day(w.index)
    key = np.where(day, w.index.normalize(), (w.index - pd.Timedelta('12h')).normalize())
    rows = []
    for node in w.columns:
        ref = x[node] if isinstance(x, pd.DataFrame) else x
        d = pd.DataFrame(dict(x=ref, y=w[node], date=key, regime=np.where(day, 'day', 'night')), index=w.index).dropna()
        for (date, regime), g in d.groupby(['date', 'regime']):
            if len(g) < min_n: continue
            k, c0 = np.polyfit(g.x, g.y, 1)
            rows.append(dict(node_id=node, day=date, regime=regime, n=len(g), bias=(g.y - g.x).mean(), slope=k, intercept=c0, r=g.x.corr(g.y)))
    return pd.DataFrame(rows)
