"""Daily leaf temperature, its rate of change and leaf minus air temperature, per node

Docs: https://franckalbinet.github.io/speaking-plants/leaf.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_leaf.ipynb.

# %% auto #0
__all__ = ['site', 'full_days', 'std_map', 'top_mask', 'daily_masks', 'batch_masks', 'no_masks', 'regular', 'smooth', 'slope',
           'leaf_series', 'sun_times', 'is_day']

# %% ../nbs/01_leaf.ipynb #55038a45
import numpy as np, pandas as pd
from scipy.signal import savgol_filter
from .clean import frames
from astral import LocationInfo
from astral.sun import sun

# %% ../nbs/01_leaf.ipynb #176025ec
def full_days(
    df:pd.DataFrame, # Output of `measurements`
    min_n:int=280, # Fewest measurements for a full day
)->pd.DataFrame: # One row per full day, with `node_id` and `day`
    "Node-days with at least `min_n` measurements"
    n = df.groupby(['node_id', df.time.dt.normalize().rename('day')]).size()
    return n[n >= min_n].reset_index()[['node_id', 'day']]

# %% ../nbs/01_leaf.ipynb #630bb15d
def std_map(
    df:pd.DataFrame, # Rows of `measurements` output
)->np.ndarray: # Shape `(24, 32)`, standard deviation of each pixel over the rows
    "Standard deviation of each pixel over time"
    return np.nanstd(frames(df), axis=0)

def top_mask(
    sd:np.ndarray, # Output of `std_map`
    q:float=0.9, # Quantile above which a pixel counts as leaf
)->np.ndarray: # Boolean, same shape as `sd`
    "Pixels whose standard deviation is above the `q` quantile"
    return sd > np.nanquantile(sd, q)

# %% ../nbs/01_leaf.ipynb #9f4dd703
def _day(df, node, day): return df[(df.node_id == node) & (df.time.dt.normalize() == day)]

def daily_masks(
    df:pd.DataFrame, # Output of `measurements`
    days:pd.DataFrame, # Output of `full_days`
    q:float=0.9, # Quantile above which a pixel counts as leaf
)->dict: # Mask per `(node_id, day)`, from that day's images
    "One leaf mask per node-day, from that day"
    return {(r.node_id, r.day): top_mask(std_map(_day(df, r.node_id, r.day)), q) for r in days.itertuples()}

def batch_masks(
    df:pd.DataFrame, # Output of `measurements`
    days:pd.DataFrame, # Output of `full_days`
    q:float=0.9, # Quantile above which a pixel counts as leaf
)->dict: # Mask per `(node_id, day)`, from all of the node's images
    "One leaf mask per node, from all its images, repeated for each of its days"
    ms = {n: top_mask(std_map(g), q) for n, g in df.groupby('node_id')}
    return {(r.node_id, r.day): ms[r.node_id] for r in days.itertuples()}

def no_masks(
    days:pd.DataFrame, # Output of `full_days`
)->dict: # All-pixel mask per `(node_id, day)`
    "Masks that keep every pixel, for the unmasked profile"
    return {(r.node_id, r.day): np.ones((24, 32), bool) for r in days.itertuples()}

# %% ../nbs/01_leaf.ipynb #fee733f2
def regular(
    s:pd.Series, # Values indexed by time
    step:str='5min', # Grid step
)->pd.Series: # Values on a grid from the first time, missing where no value is within half a step
    "Put a time series on a regular grid"
    grid = pd.date_range(s.index[0], s.index[-1], freq=step, name='time')
    return s.reindex(grid, method='nearest', tolerance=pd.Timedelta(step) / 2)

def _savgol(s, window, polyorder, deriv):
    "Savitzky-Golay filter on each stretch of `s` without missing values, per minute"
    step = s.index.freq.nanos / 60e9
    out, ok = pd.Series(np.nan, index=s.index), s.notna()
    for _, v in s[ok].groupby((ok != ok.shift()).cumsum()[ok]):
        if len(v) >= window: out[v.index] = savgol_filter(v.to_numpy(), window, polyorder, deriv=deriv, delta=step)
    return out

def smooth(
    s:pd.Series, # Output of `regular`
    window:int=13, # Points in the Savitzky-Golay window
    polyorder:int=3, # Order of the fitted polynomial
)->pd.Series: # Smoothed values, missing on stretches shorter than `window`
    "Smoothed regular series"
    return _savgol(s, window, polyorder, 0)

def slope(
    s:pd.Series, # Output of `regular`
    window:int=9, # Points in the Savitzky-Golay window
    polyorder:int=3, # Order of the fitted polynomial
)->pd.Series: # Rate of change per minute, missing on stretches shorter than `window`
    "Smoothed first derivative of a regular series"
    return _savgol(s, window, polyorder, 1)

# %% ../nbs/01_leaf.ipynb #14e508e5
def leaf_series(
    df:pd.DataFrame, # Output of `share_ruuvi`
    masks:dict, # Output of `daily_masks`, `batch_masks` or `no_masks`
    step:str='5min', # Grid step
    window:int=9, # Points in the Savitzky-Golay window of `slope`
    polyorder:int=3, # Order of the fitted polynomial
    smooth_window:int=13, # Points in the smoothing window of `t_smooth` and `dt_smooth`
)->pd.DataFrame: # One row per grid time and node-day
    "Leaf temperature and leaf minus air temperature, raw and smoothed, and the leaf slope, per node-day"
    res = []
    for (node, day), mask in masks.items():
        g = _day(df, node, day)
        t = g.time.to_numpy()
        leaf = regular(pd.Series(np.nanmedian(frames(g)[:, mask], axis=1), index=t), step)
        air = regular(pd.Series(g.ruuvi_temp.to_numpy(), index=t), step)
        res.append(pd.DataFrame(dict(node_id=node, day=day, t_leaf=leaf, t_smooth=smooth(leaf, smooth_window, polyorder),
                                     t_air=air, dt_leaf_air=leaf - air, dt_smooth=smooth(leaf - air, smooth_window, polyorder),
                                     slope=slope(leaf, window, polyorder))).reset_index())
    out = pd.concat(res, ignore_index=True)
    out.insert(3, 'hour', (out.time - out.day).dt.total_seconds() / 3600)
    return out

# %% ../nbs/01_leaf.ipynb #e3399195
site = LocationInfo('Seibersdorf', 'Austria', 'Europe/Vienna', 47.976, 16.508)

def sun_times(
    times, # Times or days, local time
    loc:LocationInfo=site, # Site of the greenhouse
)->pd.DataFrame: # One row per day, with dawn, sunrise, noon, sunset and dusk in local time
    "Sun events for each day in `times`"
    days = pd.DatetimeIndex(times).normalize().unique()
    evs = ('dawn', 'sunrise', 'noon', 'sunset', 'dusk')
    ss = [sun(loc.observer, date=d.date(), tzinfo=loc.timezone) for d in days]
    return pd.DataFrame({k: pd.to_datetime([s[k].replace(tzinfo=None) for s in ss]) for k in evs}, index=days.rename('day'))

def is_day(
    times, # Local times
    loc:LocationInfo=site, # Site of the greenhouse
)->np.ndarray: # True from sunrise to sunset
    "Whether each time is in daylight"
    t = pd.DatetimeIndex(times)
    st = sun_times(t, loc).reindex(t.normalize())
    return (t >= st.sunrise.to_numpy()) & (t < st.sunset.to_numpy())
