"""What each node was doing when: deployments, events, and checks against the logs

Docs: https://franckalbinet.github.io/speaking-plants/logbook.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_logbook.ipynb.

# %% auto #0
__all__ = ['read_deployments', 'read_events', 'assign_deployments', 'check_logbook']

# %% ../nbs/03_logbook.ipynb #fa9d3658
import numpy as np, pandas as pd
from .leaf import scene_similarity

# %% ../nbs/03_logbook.ipynb #0056d616
def read_deployments(
    path, # Path of `deployments.csv`
)->pd.DataFrame: # One row per deployment, with `start` and `end` as times, `end` missing while running
    "Read the deployments table"
    d = pd.read_csv(path, dtype=str, keep_default_na=False)
    return d.assign(start=pd.to_datetime(d.start), end=pd.to_datetime(d.end.replace('', None)))

def read_events(
    path, # Path of `events.csv`
)->pd.DataFrame: # One row per event, sorted by time
    "Read the events table"
    e = pd.read_csv(path, dtype=str, keep_default_na=False)
    return e.assign(time=pd.to_datetime(e.time)).sort_values('time', ignore_index=True)

# %% ../nbs/03_logbook.ipynb #198abe03
def assign_deployments(
    df:pd.DataFrame, # Rows with `node_id` and `time`, such as the output of `measurements`
    deps:pd.DataFrame, # Output of `read_deployments`
)->pd.DataFrame: # `df` with `deployment_id` and `plant_id` columns
    "Attach each row to the deployment that covers its node and time"
    dep, plant = pd.Series(pd.NA, index=df.index, dtype='str'), pd.Series(pd.NA, index=df.index, dtype='str')
    for r in deps.itertuples():
        m = (df.node_id == r.node_id) & (df.time >= r.start)
        if pd.notna(r.end): m &= df.time < r.end
        dep[m], plant[m] = r.deployment_id, r.plant_id
    return df.assign(deployment_id=dep, plant_id=plant)

# %% ../nbs/03_logbook.ipynb #c9cdf135
def check_logbook(
    df:pd.DataFrame, # Output of `measurements`
    deps:pd.DataFrame, # Output of `read_deployments`
    min_r:float=0.5, # Correlation below which neighbouring days count as a scene change
    min_n:int=144, # Fewest measurements for a day to be compared
)->pd.DataFrame: # One row per issue
    "Issues between the logbook and the logs"
    rows = []
    for n in sorted(set(df.node_id) - set(deps.node_id)): rows.append(dict(check='unknown node', node_id=n, detail='No deployment for this node'))
    end = deps.end.fillna(pd.Timestamp.max)
    for n, g in deps.assign(end_=end).sort_values('start').groupby('node_id'):
        for a, b in zip(g.itertuples(), list(g.itertuples())[1:]):
            if b.start < a.end_: rows.append(dict(check='overlap', node_id=n, detail=f'{a.deployment_id} and {b.deployment_id} overlap'))
    out = assign_deployments(df, deps)
    for n, g in out[out.deployment_id.isna()].groupby('node_id'):
        rows.append(dict(check='outside deployments', node_id=n, detail=f'{len(g)} rows from {g.time.min():%Y-%m-%d %H:%M} to {g.time.max():%Y-%m-%d %H:%M}'))
    days = out.assign(day=out.time.dt.normalize()).groupby(['node_id', 'day']).deployment_id.agg(lambda s: s.iloc[0] if s.nunique() == 1 else None)
    for n, sim in scene_similarity(df, min_n).items():
        for a, b in zip(sim.index, sim.index[1:]):
            r, da, db = sim.loc[a, b], days.get((n, a)), days.get((n, b))
            if r < min_r and da is not None and da == db:
                rows.append(dict(check='scene change', node_id=n, detail=f'{a:%d %b} to {b:%d %b}: r = {r:.2f}, inside {da}'))
    return pd.DataFrame(rows, columns=['check', 'node_id', 'detail'])
